security:
    encoders:
        App\Entity\Artiste:
            algorithm: bcrypt
        App\Entity\Entreprise:
                    algorithm: bcrypt

    providers:
        user_db_provider:
            entity:
                class: App\Entity\Artiste
                property: email
                class: App\Entity\Entreprise
                property: email
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                failure_path: /login
            logout:
                path: /logout
                target: /home

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:  ROLE_USER
